name: Build Godot project export templates
description: Build the Godot project export templates

inputs:

  target:
    description: Target platform
    required: true

  arch:
    description: Target platform architecture
    required: true

  # godot-version:
  #   description: The version (tag) of Godot
  #   required: true

  # type:
  #   description: Build type
  #   required: false
  #   default: release

runs:
  using: docker
  image: docker://image/nndda/gd-build:4.7-stable
  env:
    EXPORT_TARGET: ${{ inputs.target }}
    EXPORT_ARCH: ${{ inputs.arch }}

branding:
  icon: package
  color: gray-dark
